
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 22, host:2209 ##SSH merubah port SSH agar tidak bentrok dengan port SSH host
  config.vm.network "forwarded_port", guest: 3306, host: 3309 ##MySQL merubah port SSH agar tidak bentrok dengan port MySQL host

  config.vm.network "private_network", ip: "192.168.33.10" ## IP merubah alamat IP

  config.vm.synced_folder "products", "/var/www/html" ## merubah alamat folder html ke products, buat folder "products" yang setara dengan file Vagrantfile

  config.vm.provider "virtualbox" do |vb|

  end

  config.vm.provision :shell, path: "provision.sh" ## file provision jalan setelah VM siap

end

  
